add post model
Youssefares/not-zuck-not-the-twins pull request #2
Opened 2017-12-17 20:46 UTC by abdelrahmanabdelnabi

I created the initial implementation of the post model. No support for images in posts yet, I am thinking of using [paperclip](https://github.com/thoughtbot/paperclip) to add support for images.

2017-12-17 21:42 UTC, Youssefares requested changes
Paperclip is solid. Another solution is storing base64 string and using https://github.com/carrierwaveuploader/carrierwave I think.

Never mingled with these myself so research and make a decision :wink: 
Minor changes requested :+1: looks good to me.

2017-12-17 21:42 UTC, Youssefares commented on api/db/migrate/20171217200945_adding_foreign_key_contraints.rb
> +class AddingForeignKeyContraints < ActiveRecord::Migration[5.1]
We can have a better name for this migration.

2017-12-17 21:42 UTC, Youssefares commented on api/app/models/post.rb
> +  belongs_to :user
I believe  you need to add `has_many: :posts` to the User model as well.

2017-12-18 19:14 UTC, abdelrahmanabdelnabi commented
requested changes completed and resolved conflicts with master

2017-12-18 19:34 UTC, merged